/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biometria;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.geom.Line2D;
import java.awt.image.BufferedImage;
import java.awt.image.BufferedImageOp;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author David
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    DefaultListModel<String> model = new DefaultListModel<>();
    
    public Main() {
        initComponents();
        
        
    }
        BufferedImage img = new BufferedImage(360, 480, 1);
        Graphics g;
        Graphics g2;
        ArrayList<FingerPrintImage> EstadosImagenes=new ArrayList<FingerPrintImage>();
        
    File file;
    private  File seleccionarArchivo(){
        //Se crea y se muestra el JFileChooser.        
        final JFileChooser fc=new JFileChooser();
        int returnVal = fc.showOpenDialog(this);
        //En caso de seleccionar algun archivo, se procede a almacenarlo en la variable file
         if (returnVal == JFileChooser.APPROVE_OPTION) {
            file = fc.getSelectedFile();
            return file;
         }
         return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btn_gris = new javax.swing.JButton();
        panel_entrada = new javax.swing.JPanel();
        panel_img2 = new javax.swing.JPanel();
        btn_ecualizar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Cargar imagen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_gris.setText("Pasar a gris");
        btn_gris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_grisActionPerformed(evt);
            }
        });

        panel_entrada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_entrada.setPreferredSize(new java.awt.Dimension(360, 480));
        panel_entrada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_img2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_img2.setPreferredSize(new java.awt.Dimension(360, 480));
        panel_img2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ecualizar.setText("Ecualizar");
        btn_ecualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ecualizarActionPerformed(evt);
            }
        });

        jButton2.setText("Binarisar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Filtros");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Detectar minucias");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panel_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(panel_img2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_gris)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_ecualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btn_gris)
                    .addComponent(btn_ecualizar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton5)
                        .addComponent(jButton6)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_img2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_entrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static BufferedImage resize(BufferedImage img, int height, int width) {
        Image tmp = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        BufferedImage resized = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2d = resized.createGraphics();
        g2d.drawImage(tmp, 0, 0, null);
        g2d.dispose();
        return resized;
    }

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (seleccionarArchivo()!=null) {
            try {
                g=panel_entrada.getGraphics();
                img= ImageIO.read(file);
                img=resize(img, panel_entrada.getHeight(), panel_entrada.getWidth());
                g.drawImage(img, 0, 0, panel_entrada.getWidth(),panel_entrada.getHeight(),null);
                EstadosImagenes.add(new FingerPrintImage(img.getWidth(), img.getHeight()));
                model.add(0,"Seleccionada la imagen. ");
                jList.setModel(model);
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
           
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_grisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_grisActionPerformed
        // TODO add your handling code here:
        
        FingerPrintImage fg=new FingerPrintImage(img.getWidth(), img.getHeight());
        fg.ConvertiraGris(img);
        fg.Draw(panel_img2);
        EstadosImagenes.add(fg);
        model.add(0,"Pasar a gris correcto.");
        jList.setModel(model);
  
    }//GEN-LAST:event_btn_grisActionPerformed

    private void btn_ecualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ecualizarActionPerformed
        // TODO add your handling code here:
        FingerPrintImage imagenEcualizada=EstadosImagenes.get(EstadosImagenes.size()-1);

        int width = imagenEcualizada.getWidth();
        int height = imagenEcualizada.getHeight();
        int tampixel= width*height;
        int[] histograma = new int[256];
        int i =0;
        // Calculamos frecuencia relativa de ocurrencia
        // de los distintos niveles de gris en la imagen
        for (int x = 1; x < width; x++) {
            for (int y = 1; y < height; y++) {
                int valor= imagenEcualizada.getPixel(x, y);
            histograma[valor]++;
            }
        }
        int sum =0;
        // Construimos la Lookup table LUT
        float[] lut = new float[256];
        for ( i=0; i < 256; ++i ){
            sum += histograma[i];
            lut[i] = sum * 255 / tampixel;
        }
        // Se transforma la imagen utilizando la tabla LUT
        i=0;
        for (int x = 1; x < width; x++) {
            for (int y = 1; y < height; y++) {
                int valor= imagenEcualizada.getPixel(x, y);
                int valorNuevo= (int) lut[valor];
                imagenEcualizada.setPixel(x, y, valorNuevo);
                i=i+1;
            }
        }
        EstadosImagenes.add(imagenEcualizada);
        imagenEcualizada.Draw(panel_img2);
        model.add(0,"Ecualizar correcto.");
                jList.setModel(model);
    }//GEN-LAST:event_btn_ecualizarActionPerformed

    
    private FingerPrintImage binarisar(FingerPrintImage imagenEntrada,int umbral){
        FingerPrintImage imagenSalida=imagenEntrada;
        for (int i = 0; i < imagenEntrada.getWidth(); i++) {
            for (int j = 0; j < imagenEntrada.getHeight(); j++) {
                int valor=imagenEntrada.getPixel(i, j);
                if (valor<umbral) {
                    imagenSalida.setPixel(i, j, 0);
                }else{
                    imagenSalida.setPixel(i, j, 1);
                }
            }
        }
        return imagenSalida;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FingerPrintImage imagenentrada=EstadosImagenes.get(EstadosImagenes.size()-1);
        EstadosImagenes.add(binarisar(imagenentrada, (int) imagenentrada.getValorUmbral()));
        EstadosImagenes.get(EstadosImagenes.size()-1).DrawBinary(panel_img2);
        model.add(0,"Binarisar correcto.");
                jList.setModel(model);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        FingerPrintImage fpi=EstadosImagenes.get(EstadosImagenes.size()-1);
        fpi.filtroBinario1();
        model.add(0,"Filtro binario 1 correcto.");
        jList.setModel(model);

        fpi.filtroBinario2();
        fpi.DrawBinary(panel_img2);
        model.add(0,"Filtro binario 2 correcto.");
        jList.setModel(model);

        fpi.InvertirBinario();
        ZhangSuen zs=new ZhangSuen(fpi.FingerPrintImage);
        fpi.setFingerPrintImage(zs.thinImage());
        fpi.InvertirBinario();
        model.add(0,"Filtro ZhangSuen correcto.");
        jList.setModel(model);

        EstadosImagenes.add(fpi);
        fpi.DrawBinary(panel_img2);
        
        //zs.DrawBinary(panel_img2,fpi.width,fpi.height);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        FingerPrintImage copia=EstadosImagenes.get(EstadosImagenes.size()-1);
        copia.InvertirBinario();
        copia.DetectarMinutias(panel_img2,jList);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ecualizar;
    private javax.swing.JButton btn_gris;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JList<String> jList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_entrada;
    private javax.swing.JPanel panel_img2;
    // End of variables declaration//GEN-END:variables
}
